## Examples of List Creation

In [2]:
simple_list = [1,2,3]

In [3]:
simple_list

[1, 2, 3]

In [4]:
print(simple_list)

[1, 2, 3]


In [5]:
list2 = simple_list
print(list2)
print(simple_list)
list2[1] = 0
print(list2)
print(simple_list)

[1, 2, 3]
[1, 2, 3]
[1, 0, 3]
[1, 0, 3]


## Copy function is used to copy the data in another list

In [6]:
list3 = simple_list.copy()
print(list3)
print(simple_list)
list3[0] = 'abc'
print(list3)
print(simple_list)

[1, 0, 3]
[1, 0, 3]
['abc', 0, 3]
[1, 0, 3]


In [7]:
counter = 0
simple_list = [1,2,564,8,456,2,3]
for i in simple_list:
    print(i)
    counter = counter + 2
    

1
2
564
8
456
2
3


In [8]:
for i in simple_list[1:4]:
    for j in simple_list[4:6]:
        print(i*j)
    print('outside j loop')
print('outside both loops')

912
4
outside j loop
257184
1128
outside j loop
3648
16
outside j loop
outside both loops


In [9]:
print(range(6))

range(0, 6)


In [10]:
'1' + '1'

'11'

In [11]:
import numpy as np

In [12]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.20)))

-1.0
1.1
5.2


In [13]:
vec = np.array([1,2,3])
print(vec)
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(' ')
print(mat)
print(' ')
print(mat.T)

[1 2 3]
 
[[1 2 1]
 [4 5 9]
 [1 8 9]]
 
[[1 4 1]
 [2 5 8]
 [1 9 9]]


##  arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.

In [14]:
vec2 = np.arange(0,15)
print(vec2)
print(' ')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 
[ 3  9 15]


## The linspace() function returns evenly spaced numbers over a specified interval [start, stop]. The endpoint of the interval can optionally be excluded.

In [15]:
vec4 = np.linspace(0,5,10)
print(vec4)
print(' ')
print(vec4.reshape(5,2))
vec4

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
 
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## The zeros() function is used to get a new array of given shape and type, filled with zeros.

In [16]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones([3,5])
print(' ')
print(mat3)
mat4 = np.eye(5)
print(' ')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5 + vec6)
print(vec5*vec6)
print(vec5/vec6)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[0.33333333 0.5        0.6        0.66666667 0.71428571]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [18]:
print(mat)
print(' ')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]
 
[1 2 3]

[ 8 41 44]


## This function is used to compute the eigenvalues and right eigenvectors of a square array.

In [19]:
print(np.linalg.solve(mat,product))
print(' ')
print(np.linalg.inv(mat))

[1. 2. 3.]
 
[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [20]:
vec7 = np.array(['blue','red','orange','purple','purple','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


## The rand() function creates an array of specified shape and fills it with random values.

In [21]:
rand_mat = np.random.rand(5,5)
print(rand_mat)
rand_mat2 = np.random.randn(10,5)
print(' ')
print(rand_mat2)

[[0.32769425 0.25117306 0.97466849 0.12821317 0.51536507]
 [0.27558251 0.38816518 0.46371293 0.39562372 0.76970604]
 [0.78626431 0.67346538 0.17559911 0.17413642 0.30624003]
 [0.00762984 0.66386083 0.96023403 0.10800275 0.14501008]
 [0.82130462 0.07832294 0.88413852 0.69989815 0.8537247 ]]
 
[[-1.68412776  1.18045501  0.19269651  1.97165858  1.18022525]
 [-0.96537262 -0.38737299  0.14123202  0.80333325  0.23739523]
 [ 0.03311744  1.42051741  0.65922982 -2.0173948   0.240063  ]
 [ 2.10009913 -0.62172475 -0.65601234  0.96929831  0.37882251]
 [-0.34668619 -0.21061925 -2.08696926 -1.5041294   0.55883627]
 [-1.11295374  0.59869785  0.30943063  0.63022812  0.73853529]
 [-0.2117048  -0.2092118   1.66041482 -1.07526103 -0.17514748]
 [-0.14552167 -0.26839931 -2.18032806 -0.98172378  1.46822502]
 [-0.67605888 -1.8245928   0.0692358  -0.1027133   0.15616615]
 [ 0.79561997  1.03319681 -0.89854674 -0.46957296 -0.87811448]]


## The mean() in Python gives the average values. 
## The std() in Python gives the standard deviation values.

In [22]:
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4731094456323436
1.0315350234710625


## Max() - Returns maximum value
## Min() - Returns minimum value

In [23]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.007629842714842794
2.100099134243848


Accessing entries to numpy arrays

In [24]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.01156617 -0.29163559 -1.64386995 -0.55859159 -1.25049994 -1.39303599
 -1.37925702 -0.94547583  0.71956684  0.24199785 -0.58611452  1.90863318
 -0.96726538  0.13915587 -1.23360464  0.57048955 -1.20096792  0.37417394
  0.2015296 ]
-1.37925702255984


In [25]:
print(rand_vec[4:9])

[-1.25049994 -1.39303599 -1.37925702 -0.94547583  0.71956684]


In [26]:
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.01156617 -0.55859159 -1.37925702  0.24199785 -0.96726538]


In [27]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.32769425 0.25117306 0.97466849 0.12821317 0.51536507]
 [0.27558251 0.38816518 0.46371293 0.39562372 0.76970604]
 [0.78626431 0.67346538 0.17559911 0.17413642 0.30624003]
 [0.00762984 0.66386083 0.96023403 0.10800275 0.14501008]
 [0.82130462 0.07832294 0.88413852 0.69989815 0.8537247 ]]
0.46371293467515473
0.46371293467515473


In [28]:
print(rand_mat[0:2,1:3])

[[0.25117306 0.97466849]
 [0.38816518 0.46371293]]


In [29]:
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.01156617 -0.29163559 -1.64386995 -0.55859159 -1.25049994 -1.39303599
 -1.37925702 -0.94547583  0.71956684  0.24199785 -0.58611452  1.90863318
 -0.96726538  0.13915587 -1.23360464  0.57048955 -1.20096792  0.37417394
  0.2015296 ]

[ 0.01156617 -0.29163559 -1.64386995  4.          4.         -1.39303599
 -1.37925702 -0.94547583  0.71956684  0.24199785 -0.58611452  1.90863318
 -0.96726538  0.13915587 -1.23360464  0.57048955 -1.20096792  0.37417394
  0.2015296 ]

[ 0.01156617 -0.29163559 -1.64386995  1.          2.         -1.39303599
 -1.37925702 -0.94547583  0.71956684  0.24199785 -0.58611452  1.90863318
 -0.96726538  0.13915587 -1.23360464  0.57048955 -1.20096792  0.37417394
  0.2015296 ]


In [30]:
print(rand_mat)
rand_mat[1:3,3:5]=0
print('')
print(rand_mat)

[[0.32769425 0.25117306 0.97466849 0.12821317 0.51536507]
 [0.27558251 0.38816518 0.46371293 0.39562372 0.76970604]
 [0.78626431 0.67346538 0.17559911 0.17413642 0.30624003]
 [0.00762984 0.66386083 0.96023403 0.10800275 0.14501008]
 [0.82130462 0.07832294 0.88413852 0.69989815 0.8537247 ]]

[[0.32769425 0.25117306 0.97466849 0.12821317 0.51536507]
 [0.27558251 0.38816518 0.46371293 0.         0.        ]
 [0.78626431 0.67346538 0.17559911 0.         0.        ]
 [0.00762984 0.66386083 0.96023403 0.10800275 0.14501008]
 [0.82130462 0.07832294 0.88413852 0.69989815 0.8537247 ]]


In [31]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[0.32769425 0.25117306 0.97466849]
 [0.27558251 0.38816518 0.46371293]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [32]:
print(rand_mat)

[[3.         3.         3.         0.12821317 0.51536507]
 [3.         3.         3.         0.         0.        ]
 [0.78626431 0.67346538 0.17559911 0.         0.        ]
 [0.00762984 0.66386083 0.96023403 0.10800275 0.14501008]
 [0.82130462 0.07832294 0.88413852 0.69989815 0.8537247 ]]


In [33]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.12821317 0.51536507]
 [3.         3.         3.         0.         0.        ]
 [0.78626431 0.67346538 0.17559911 0.         0.        ]
 [0.00762984 0.66386083 0.96023403 0.10800275 0.14501008]
 [0.82130462 0.07832294 0.88413852 0.69989815 0.8537247 ]]


## Saving and Loading NumPy Arrays


In [34]:
rand_vec = np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.00380164 -1.41532315 -0.76097676  0.84588984  0.16668053 -0.21893073
 -0.00275106  1.96407604 -0.59133303 -0.35435128  1.51562923 -0.51061597
  1.19316229  0.48142834 -0.1196673 ]
[ True False False  True  True False False  True False False  True False
  True  True False]
[0.00380164 0.84588984 0.16668053 1.96407604 1.51562923 1.19316229
 0.48142834]


In [35]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-1.68412776  1.18045501  0.19269651  1.97165858  1.18022525]
 [-0.96537262 -0.38737299  0.14123202  0.80333325  0.23739523]
 [ 0.03311744  1.42051741  0.65922982 -2.0173948   0.240063  ]
 [ 2.10009913 -0.62172475 -0.65601234  0.96929831  0.37882251]
 [-0.34668619 -0.21061925 -2.08696926 -1.5041294   0.55883627]
 [-1.11295374  0.59869785  0.30943063  0.63022812  0.73853529]
 [-0.2117048  -0.2092118   1.66041482 -1.07526103 -0.17514748]
 [-0.14552167 -0.26839931 -2.18032806 -0.98172378  1.46822502]
 [-0.67605888 -1.8245928   0.0692358  -0.1027133   0.15616615]
 [ 0.79561997  1.03319681 -0.89854674 -0.46957296 -0.87811448]]
[1.18045501 0.19269651 1.97165858 1.18022525 0.14123202 0.80333325
 0.23739523 0.03311744 1.42051741 0.65922982 0.240063   2.10009913
 0.96929831 0.37882251 0.55883627 0.59869785 0.30943063 0.63022812
 0.73853529 1.66041482 1.46822502 0.0692358  0.15616615 0.79561997
 1.03319681]


In [36]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.00380164 -1.41532315 -0.76097676  0.84588984  0.16668053 -0.21893073
 -0.00275106  1.96407604 -0.59133303 -0.35435128  1.51562923 -0.51061597
  1.19316229  0.48142834 -0.1196673 ]

[ 3.80163798e-03 -1.41532315e+00 -7.60976758e-01 -5.00000000e+00
  1.66680527e-01 -2.18930729e-01 -2.75105510e-03 -5.00000000e+00
 -5.91333032e-01 -3.54351278e-01 -5.00000000e+00 -5.10615966e-01
 -5.00000000e+00  4.81428338e-01 -1.19667302e-01]


In [37]:
np.save('saved_file_name',rand_mat2)

In [38]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

## PANDAS

### COMBINING DATA FRAMES

In [39]:
import pandas as pd

In [40]:
df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [41]:
#combining the data frames using concat fn. in multiple ways
pd.concat([df7,df8],axis=1,sort=False)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

In [42]:
pd.concat([df7,df8],axis=0,sort=False)

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
4      101      NaN       NaN    123  yellow      12.0
5      103      NaN       NaN    214   green       9.0
6      104      NaN       NaN    663   green      44.0
7      105      NaN       NaN    331    blue      21.0

In [43]:
pd.concat([df7,df8],axis=1,sort=True)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

In [44]:
pd.concat([df7,df8],axis=0,sort=True)

category   color customer  distance important  sales
0     cat2     NaN      101       NaN       yes    123
1     cat2     NaN      102       NaN        no     52
2     cat1     NaN      103       NaN       yes    214
3     cat3     NaN      104       NaN       yes    663
4      NaN  yellow      101      12.0       NaN    123
5      NaN   green      103       9.0       NaN    214
6      NaN   green      104      44.0       NaN    663
7      NaN    blue      105      21.0       NaN    331

## MERGE AND JOINS

### MERGE : 

In [45]:
pd.merge(df7,df8,how='outer',on='customer')

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [46]:
pd.merge(df7,df8,how='inner',on='customer') #for inner merge it fucuses on similar columns, i.e, 
                                            #no NAN values, in this case Customer 102 & 105 is not included in the oporation

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [47]:
pd.merge(df7,df8,how='left',on='customer') # only takes cols present in left df that is df7

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow      12.0    123.0
1      102     cat2        no       52     NaN       NaN      NaN
2      103     cat1       yes      214   green       9.0    214.0
3      104     cat3       yes      663   green      44.0    663.0

In [48]:
pd.merge(df7,df8,how='right',on='customer') # only takes cols present in right df that is df8

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

### JOIN : Combines on Index

In [49]:
df9 = pd.DataFrame({'Q1': [101,102,103],
                    'Q2': [201,202,203]},
                   index=['I0','I1','I2'])

df10 = pd.DataFrame({'Q3': [301,302,303],
                    'Q4': [401,402,403]},
                   index=['I0','I2','I3'])

In [50]:
df9.join(df10,how='outer')  #is a union will get all the values

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2  103.0  203.0  302.0  402.0
I3    NaN    NaN  303.0  403.0

In [51]:
df9.join(df10,how='inner')

Q1   Q2   Q3   Q4
I0  101  201  301  401
I2  103  203  302  402

In [52]:
df9.join(df10,how='right')

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

In [53]:
df9.join(df10,how='left')

Q1   Q2     Q3     Q4
I0  101  201  301.0  401.0
I1  102  202    NaN    NaN
I2  103  203  302.0  402.0

FUNCTIONS 


In [54]:
df8['color'].unique() #gives the unique values of the given key from the dict as df8

array(['yellow', 'green', 'blue'], dtype=object)

In [55]:
df8['color'].value_counts() #counts the occurence of the values

green     2
blue      1
yellow    1
Name: color, dtype: int64

In [56]:
df9

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [57]:
df9.mean()

Q1    102.0
Q2    202.0
dtype: float64

In [58]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [59]:
df8.columns #gives the column labes 

Index(['customer', 'color', 'distance', 'sales'], dtype='object')

In [60]:
new_def = df8[(df8['customer']!='105') & (df8['color']!='green')]
new_def

customer   color  distance  sales
4      101  yellow        12    123

In [61]:
print(df8['sales'].mean())
print(df8['distance'].min())
print(df8['distance'].max())
print(df8['sales'].std())
print(df8['sales'].sum())

332.75
9
44
236.05419575456256
1331


In [62]:
def profit(s):
    return s*0.5

In [63]:
df8['sales'].apply(profit)

4     61.5
5    107.0
6    331.5
7    165.5
Name: sales, dtype: float64

In [64]:
df8['color'].apply(len)

4    6
5    5
6    5
7    4
Name: color, dtype: int64

In [65]:
df11 = df8[['distance','sales']]
df11.applymap(profit) #applymap only works entry by entry doesn't work on series

distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5

In [66]:
def col_sum(co):
    return sum(co)
df11.apply(col_sum)

distance      86
sales       1331
dtype: int64

In [67]:
del df8['color']
df8

customer  distance  sales
4      101        12    123
5      103         9    214
6      104        44    663
7      105        21    331

In [68]:
df8.index

Int64Index([4, 5, 6, 7], dtype='int64')

In [69]:
df8.sort_values(by='distance')

customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663

In [70]:
df8

customer  distance  sales
4      101        12    123
5      103         9    214
6      104        44    663
7      105        21    331

In [71]:
df8.sort_values(by='distance', inplace=True)

In [72]:
df8

customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663

GROUPBY 

In [73]:
# if some series has multiple of the same value then we can group all the unique entries together
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])
df6

customer  product1  product2
Purchase 1  Customer 1       1.1      8.20
Purchase 2  Customer 1       2.1      9.10
Purchase 3   Customer2       3.8     11.10
Purchase 4   Customer2       4.2      5.20
Purchase 5   Customer3       5.5     44.66
Purchase 6   Customer3       6.9    983.00

In [74]:
grouped_data = df6.groupby('customer')
print(grouped_data)

In [75]:
grouped_data.describe() #gives a pivot table

product1                                           product2  \
              count mean       std  min   25%  50%   75%  max    count   
customer                                                                 
Customer 1      2.0  1.6  0.707107  1.1  1.35  1.6  1.85  2.1      2.0   
Customer2       2.0  4.0  0.282843  3.8  3.90  4.0  4.10  4.2      2.0   
Customer3       2.0  6.2  0.989949  5.5  5.85  6.2  6.55  6.9      2.0   

                                                                        
              mean         std    min      25%     50%      75%    max  
customer                                                                
Customer 1    8.65    0.636396   8.20    8.425    8.65    8.875    9.1  
Customer2     8.15    4.171930   5.20    6.675    8.15    9.625   11.1  
Customer3   513.83  663.506577  44.66  279.245  513.83  748.415  983.0

In [76]:
df8.to_csv('df8.csv',index=True)  #will save the index in a diff. col

In [77]:
new_df8 = pd.read_csv('df8.csv',index_col=0)
new_df8

customer  distance  sales
5       103         9    214
4       101        12    123
7       105        21    331
6       104        44    663

In [78]:
new_df8 = pd.read_csv('df8.csv',index_col=1)
new_df8

Unnamed: 0  distance  sales
customer                             
103                5         9    214
101                4        12    123
105                7        21    331
104                6        44    663

In [79]:
new_df8 = pd.read_csv('df8.csv')
new_df8

Unnamed: 0  customer  distance  sales
0           5       103         9    214
1           4       101        12    123
2           7       105        21    331
3           6       104        44    663

In [80]:
df8.to_excel('df8.xlsx',index=False,sheet_name='first sheet')

In [81]:
nw_df8 = pd.read_excel('df8.xlsx',sheet_name='first sheet',index_col=0)
nw_df8

distance  sales
customer                 
103              9    214
101             12    123
105             21    331
104             44    663

In [82]:
import os

In [83]:
os.getcwd()

'C:\\Users\\Admin\\Desktop\\Python for Data Science GL\\GL Python study mats\\02_Numpy'